language: android
android:
  components:
    - android-24
    - build-tools-L
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
jdk: oraclejdk8
